package com.obfuscator.processor;

import com.obfuscator.util.NameGenerator;
import org.objectweb.asm.*;

public class Level1BasicObfuscator {

    private final NameGenerator nameGenerator = new NameGenerator();

    /**
     * Pre-scan pass: walks only method declarations (SKIP_CODE) and registers
     * the obfuscated name for every private non-special method so that call-site
     * remapping in visitMethodInsn works correctly regardless of declaration order.
     */
    public void preRegisterMethods(ClassReader reader) {
        reader.accept(new ClassVisitor(Opcodes.ASM9) {
            private String className;

            @Override
            public void visit(int version, int access, String name, String signature,
                             String superName, String[] interfaces) {
                this.className = name;
            }

            @Override
            public MethodVisitor visitMethod(int access, String name, String descriptor,
                                            String signature, String[] exceptions) {
                boolean isPrivate = (access & Opcodes.ACC_PRIVATE) != 0;
                boolean isSpecial = name.equals("<init>") || name.equals("<clinit>")
                        || name.startsWith("$")
                        || name.startsWith("lambda$")
                        || name.startsWith("access$");
                if (isPrivate && !isSpecial) {
                    nameGenerator.generateObfuscatedName(
                        className + "." + name + descriptor, "m");
                }
                return null; // skip body
            }
        }, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
    }

    public ClassVisitor createVisitor(ClassVisitor cv) {
        return new ClassVisitor(Opcodes.ASM9, cv) {

            private String className;

            @Override
            public void visit(int version, int access, String name, String signature,
                            String superName, String[] interfaces) {
                this.className = name;
                super.visit(version, access, name, signature, superName, interfaces);
            }

            @Override
            public FieldVisitor visitField(int access, String name, String descriptor,
                                          String signature, Object value) {
                if ((access & Opcodes.ACC_PRIVATE) != 0 && !name.startsWith("this$")) {
                    String obfuscatedName = nameGenerator.generateObfuscatedName(
                        className + "." + name, "f");
                    return super.visitField(access, obfuscatedName, descriptor, signature, value);
                }
                return super.visitField(access, name, descriptor, signature, value);
            }

            @Override
            public MethodVisitor visitMethod(int access, String name, String descriptor,
                                            String signature, String[] exceptions) {
                String methodName = name;

                boolean isPrivate = (access & Opcodes.ACC_PRIVATE) != 0;
                boolean isSpecial = name.equals("<init>") || name.equals("<clinit>")
                        || name.startsWith("$")        // enum: $values(), and similar JVM synthetics
                        || name.startsWith("lambda$")  // lambda bodies generated by javac
                        || name.startsWith("access$"); // inner-class access bridge methods

                if (isPrivate && !isSpecial) {
                    methodName = nameGenerator.generateObfuscatedName(
                        className + "." + name + descriptor, "m");
                }

                MethodVisitor mv = super.visitMethod(access, methodName, descriptor,
                                                     signature, exceptions);

                final String finalMethodName = methodName;
                return new MethodVisitor(Opcodes.ASM9, mv) {

                    @Override
                    public void visitFieldInsn(int opcode, String owner, String name, String descriptor) {
                        // Remap GETFIELD/PUTFIELD references for fields declared in this class
                        if (owner.equals(className)) {
                            String mapped = nameGenerator.getMappedName(className + "." + name);
                            if (mapped != null) {
                                name = mapped;
                            }
                        }
                        super.visitFieldInsn(opcode, owner, name, descriptor);
                    }

                    @Override
                    public void visitMethodInsn(int opcode, String owner, String name,
                                               String descriptor, boolean isInterface) {
                        // Remap call sites for private methods we renamed in this class
                        if (owner.equals(className)) {
                            String mapped = nameGenerator.getMappedName(
                                className + "." + name + descriptor);
                            if (mapped != null) {
                                name = mapped;
                            }
                        }
                        super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
                    }

                    @Override
                    public void visitInvokeDynamicInsn(String name, String descriptor,
                                                       Handle bootstrapMethodHandle,
                                                       Object... bootstrapMethodArguments) {
                        // Remap method references (e.g. this::connectionLoop) that were
                        // renamed by Level1. The bootstrap args contain Handle objects
                        // pointing to the actual target method — update those too.
                        for (int i = 0; i < bootstrapMethodArguments.length; i++) {
                            if (bootstrapMethodArguments[i] instanceof Handle h) {
                                if (h.getOwner().equals(className)) {
                                    String mapped = nameGenerator.getMappedName(
                                        className + "." + h.getName() + h.getDesc());
                                    if (mapped != null) {
                                        bootstrapMethodArguments[i] = new Handle(
                                            h.getTag(), h.getOwner(), mapped,
                                            h.getDesc(), h.isInterface());
                                    }
                                }
                            }
                        }
                        super.visitInvokeDynamicInsn(name, descriptor,
                            bootstrapMethodHandle, bootstrapMethodArguments);
                    }

                    @Override
                    public void visitLocalVariable(String varName, String descriptor,
                                                   String signature, Label start, Label end, int index) {
                        if (!varName.equals("this")) {
                            varName = nameGenerator.generateObfuscatedName(
                                className + "." + finalMethodName + "." + varName, "v");
                        }
                        super.visitLocalVariable(varName, descriptor, signature, start, end, index);
                    }
                };
            }
        };
    }
}
